### PR TITLE
Begin to use single setup.py files

### PR DESCRIPTION
**Pull request by capooti**
I began working on the proposed solution.
@francbartoli @ricardogsilva please have a look at this

### CODE REVIEW

**Comment by capooti** [comment]
refs #1

**Comment by capooti** [comment]
@ricardogsilva I believe we would need to include each of them when building each single package. So we are sure that each pypi package will have its license

**Comment by ricardogsilva** [comment]
How do you envisage this pypi package generation for each contrib? Perhaps that method will be somewhat automated and would be able to pull the single `LICENSE` file from the repo root? Or maybe we tackle this problem whenever we get to that point in the future then.

IMO perhaps it might be overkill to publish individual contrib apps to pypi, as it places an additional maintenance burden on all of them. Anyway, this should probably be discussed with a more broad audience. In order to move forward I'm dismissing my earlier request concerning the LICENSE file then.

**Comment by francbartoli** [comment]
I agree with you @capooti while I would remove the top level license file otherwise it would look like to me we are forcing developers towards one single license

**Comment by ricardogsilva** [comment]
@francbartoli 
I'm not a lawyer, but from my limited understanding of the GPL, I guess we are indeed forcing devs towards one single license - AFAICT since GeoNode is GPL, then its contrib packages must also have the same license.

I'd love to get a clarification on this from someone more knowledgeable though

**Comment by francbartoli** [comment]
@ricardogsilva far from an expert but once you can install them as pypi packages I believe they might have different licenses. As an instance let's take your module which is extending the django-auth-ldap with a BSD more permissive license. I believe you can obviously use GPL which is compatible but I guess you might still stay with BSD without breaking any rule. Otherwise, I cannot explain why you would be allowed to use the original django module as it is in GeoNode or in any other Django application which requires ldap authentication.

**Pull request merged**
